version: '3.8'

services:
  backend:
    env_file:
      - api/.env
    build:
      context: ./api/
      dockerfile: .dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./api/data/:/api/data/

  frontend:
    build:
      context: ./client/
      dockerfile: .dockerfile
    ports:
      - "3000:3000"
    restart: always